// M9 Phase 2 -- Non-Secure Callable (NSC) veneer entries.
//
// Each function with __attribute__((cmse_nonsecure_entry)) gets a 4-byte
// SG (Secure Gateway) stub emitted into the .gnu.sgstubs section, which
// memmap_secure.ld places at the NSC base (0x1007F000, exactly the SAU
// R0 range). When NS code calls one of these symbols it jumps to the SG
// stub, which transitions the CPU to Secure state and invokes the real
// function body in Secure flash.
//
// Rules for veneers:
//   - Every NS pointer parameter MUST be validated with
//     cmse_check_pointed_object() before deref. Refuse if any output
//     buffer overlaps Secure memory (cmse returns NULL).
//   - Return values are either scalars or NS-writable out-buffers; never
//     a pointer into Secure-side rodata (NS can't read S memory).
//   - Side effects must be safe under partial validation: if input is
//     bogus, return early without touching S state.
//
// The picowallet binary (NS image) links against the import library
// generated by `--cmse-implib --out-implib=...` during the Secure link
// to resolve these symbols.

#include <stdint.h>
#include <stddef.h>
#include <arm_cmse.h>

#include "os/secure_api.h"

// --- Phase 2a smoke-test veneer -------------------------------------------
//
// Round-trips a value with a known bit-flip so NS can verify the SG path
// works end-to-end before any real veneers go in. Remove once Phase 2b
// (chains/HWM) is shipping.
__attribute__((cmse_nonsecure_entry))
uint32_t s_phase2_test(uint32_t x) {
    return x ^ 0xA5A5A5A5u;
}
