// M9 Phase 2 -- Non-Secure Callable (NSC) veneer entries.
//
// Each function with __attribute__((cmse_nonsecure_entry)) gets a 4-byte
// SG (Secure Gateway) stub emitted into the .gnu.sgstubs section, which
// memmap_secure.ld places at the NSC base (0x1007F000, exactly the SAU
// R0 range). When NS code calls one of these symbols it jumps to the SG
// stub, which transitions the CPU to Secure state and invokes the real
// function body in Secure flash.
//
// Rules for veneers:
//   - Every NS pointer parameter MUST be validated with
//     cmse_check_pointed_object() before deref. Refuse if any output
//     buffer overlaps Secure memory (cmse returns NULL).
//   - Return values are either scalars or NS-writable out-buffers; never
//     a pointer into Secure-side rodata (NS can't read S memory).
//   - Side effects must be safe under partial validation: if input is
//     bogus, return early without touching S state.
//
// The picowallet binary (NS image) links against the import library
// generated by `--cmse-implib --out-implib=...` during the Secure link
// to resolve these symbols.

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <arm_cmse.h>

#include "hardware/flash.h"
#include "hardware/sync.h"

#include "os/api.h"
#include "os/secure_api.h"
#include "os/storage/flash_layout.h"

// Phase 2c: signing veneers reach into Secure-side keystore.c which has
// the seed + SLIP-10 + Ed25519 + SHA-512 (all compiled only into the
// Secure target via PICOWALLET_SECURE_BUILD).
extern int os_crypto_get_pubkey(os_curve_t curve, const char *path,
                                uint8_t *out_pubkey, size_t out_size,
                                size_t *out_len);
extern int os_crypto_sign(os_curve_t curve, const char *path,
                          const uint8_t *data, size_t data_len,
                          uint8_t out_sig[64]);

// HWM layout constants -- mirror hwm_flash.c. Phase 2c will fold this into
// a single Secure-side storage module once the keystore moves over.
#define HWM_SECTOR_SIZE        4096u
#define HWM_TOTAL_SLOTS_LOCAL  16u
#define HWM_SECTORS_PER_SLOT   (HWM_FLASH_SIZE / HWM_SECTOR_SIZE / HWM_TOTAL_SLOTS_LOCAL)
#define HWM_BYTES_PER_SLOT     (HWM_SECTORS_PER_SLOT * HWM_SECTOR_SIZE)

// --- Phase 2a smoke-test veneer -------------------------------------------
//
// Round-trips a value with a known bit-flip so NS can verify the SG path
// works end-to-end before any real veneers go in. Remove once Phase 2b
// (chains/HWM) is shipping.
__attribute__((cmse_nonsecure_entry))
uint32_t s_phase2_test(uint32_t x) {
    return x ^ 0xA5A5A5A5u;
}

// --- Phase 2b: flash veneers --------------------------------------------
//
// Each function below is a Secure Gateway entry into Secure flash code.
// The pointer-bearing veneers MUST validate the buffer is in NS memory
// before reading. cmse_check_pointed_object() returns NULL if the buffer
// straddles Secure memory or is not NS-readable, in which case the
// veneer refuses with NEG_PTR. This is the M9 boundary's primary
// argument-validation primitive.
#define M9_NEG_PTR    (-101)
#define M9_NEG_RANGE  (-102)

__attribute__((cmse_nonsecure_entry))
int s_flash_write_chains_page(const void *page, size_t len) {
    if (len != CHAINS_FLASH_SIZE) return M9_NEG_RANGE;
    const void *checked = cmse_check_address_range(
        (void *)page, len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!checked) return M9_NEG_PTR;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(CHAINS_FLASH_OFFSET, CHAINS_FLASH_SIZE);
    flash_range_program(CHAINS_FLASH_OFFSET, (const uint8_t *)checked, len);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_slot(uint8_t slot_idx) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    uint32_t off = HWM_FLASH_OFFSET + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(off, HWM_BYTES_PER_SLOT);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_sector(uint8_t slot_idx, uint8_t sector_in_slot) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    if (sector_in_slot >= HWM_SECTORS_PER_SLOT) return M9_NEG_RANGE;
    uint32_t off = HWM_FLASH_OFFSET
                 + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT
                 + (uint32_t)sector_in_slot * HWM_SECTOR_SIZE;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(off, HWM_SECTOR_SIZE);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_all(void) {
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(HWM_FLASH_OFFSET, HWM_FLASH_SIZE);
    restore_interrupts(ints);
    return 0;
}

// --- Phase 2c: keystore-backed signing veneers -------------------------
//
// Walks an NS-supplied SLIP-10 path string through the Secure-side seed
// (TEST_SEED, replaced by encrypted+PIN-unlocked seed in M9.5) and
// returns the public key (s_get_pubkey) or a 32-byte SC-challenge
// signature (s_sign_sc_challenge). Privval canonical sign-bytes routes
// through the larger HWM-fused veneer (Phase 2c3).
//
// The path string is treated as length-bounded by KEYSTORE_MAX_PATH_LEN
// scanning during cmse_check_address_range; we pass a generous upper
// bound and the keystore's own parser bails on anything malformed.
#define M9_KEYSTORE_MAX_PATH_LEN  128u

__attribute__((cmse_nonsecure_entry))
int s_get_pubkey(uint8_t curve, const char *path, uint8_t out_pubkey[32]) {
    if (!path || !out_pubkey) return M9_NEG_PTR;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *out_chk = cmse_check_address_range(
        out_pubkey, 32, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!out_chk) return M9_NEG_PTR;
    size_t out_len = 0;
    return os_crypto_get_pubkey((os_curve_t)curve, path, out_pubkey, 32, &out_len);
}

__attribute__((cmse_nonsecure_entry))
int s_sign_privval(const char *path, const uint8_t *data, size_t data_len,
                   uint8_t out_sig[64]) {
    if (!path || !data || !out_sig) return M9_NEG_PTR;
    if (data_len == 0 || data_len > 4096u) return M9_NEG_RANGE;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *data_chk = cmse_check_address_range(
        (void *)data, data_len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!data_chk) return M9_NEG_PTR;
    const void *sig_chk = cmse_check_address_range(
        out_sig, 64, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!sig_chk) return M9_NEG_PTR;
    // Curve is fixed to Ed25519 here; the privval protocol on both
    // Cosmos and Gno chains uses Ed25519 only. cmse_nonsecure_entry's
    // 4-register limit forced dropping the curve arg.
    return os_crypto_sign(OS_CURVE_ED25519, path, data, data_len, out_sig);
}

__attribute__((cmse_nonsecure_entry))
int s_sign_sc_challenge(uint8_t curve, const char *path,
                        const uint8_t challenge[32], uint8_t out_sig[64]) {
    if (!path || !challenge || !out_sig) return M9_NEG_PTR;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *chal_chk = cmse_check_address_range(
        (void *)challenge, 32, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!chal_chk) return M9_NEG_PTR;
    const void *sig_chk = cmse_check_address_range(
        out_sig, 64, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!sig_chk) return M9_NEG_PTR;
    // Length-locked to 32 bytes here: this veneer cannot be turned into
    // a general-purpose signing oracle. Privval canonical sign-bytes
    // (variable length) route through Phase 2c3's s_sign_and_advance.
    return os_crypto_sign((os_curve_t)curve, path, challenge, 32, out_sig);
}

__attribute__((cmse_nonsecure_entry))
int s_flash_write_hwm_page(uint8_t slot_idx, uint16_t page_in_slot,
                           const void *page, size_t len) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    if (len != 256u) return M9_NEG_RANGE;        // pico-sdk FLASH_PAGE_SIZE
    uint32_t slot_pages = HWM_BYTES_PER_SLOT / 256u;
    if (page_in_slot >= slot_pages) return M9_NEG_RANGE;
    const void *checked = cmse_check_address_range(
        (void *)page, len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!checked) return M9_NEG_PTR;
    uint32_t off = HWM_FLASH_OFFSET
                 + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT
                 + (uint32_t)page_in_slot * 256u;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_program(off, (const uint8_t *)checked, len);
    restore_interrupts(ints);
    return 0;
}
