// M9 Phase 2 -- Non-Secure Callable (NSC) veneer entries.
//
// Each function with __attribute__((cmse_nonsecure_entry)) gets a 4-byte
// SG (Secure Gateway) stub emitted into the .gnu.sgstubs section, which
// memmap_secure.ld places at the NSC base (0x1007F000, exactly the SAU
// R0 range). When NS code calls one of these symbols it jumps to the SG
// stub, which transitions the CPU to Secure state and invokes the real
// function body in Secure flash.
//
// Rules for veneers:
//   - Every NS pointer parameter MUST be validated with
//     cmse_check_pointed_object() before deref. Refuse if any output
//     buffer overlaps Secure memory (cmse returns NULL).
//   - Return values are either scalars or NS-writable out-buffers; never
//     a pointer into Secure-side rodata (NS can't read S memory).
//   - Side effects must be safe under partial validation: if input is
//     bogus, return early without touching S state.
//
// The picowallet binary (NS image) links against the import library
// generated by `--cmse-implib --out-implib=...` during the Secure link
// to resolve these symbols.

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <arm_cmse.h>

#include "hardware/flash.h"
#include "hardware/sync.h"

#include "os/api.h"
#include "os/secure_api.h"
#include "os/mode.h"
#include "os/storage/chains.h"
#include "os/storage/flash_layout.h"
#include "os/storage/hwm_flash.h"
#include "os/hal/display.h"
#include "os/ui/splash.h"
#include "os/ui/console.h"
#include "os/ui/mode_select.h"
#include "os/ui/factory_reset.h"

// Phase 2c: signing veneers reach into Secure-side keystore.c which has
// the seed + SLIP-10 + Ed25519 + SHA-512 (all compiled only into the
// Secure target via PICOWALLET_SECURE_BUILD).
extern int os_crypto_get_pubkey(os_curve_t curve, const char *path,
                                uint8_t *out_pubkey, size_t out_size,
                                size_t *out_len);
extern int os_crypto_sign(os_curve_t curve, const char *path,
                          const uint8_t *data, size_t data_len,
                          uint8_t out_sig[64]);

// HWM layout constants -- mirror hwm_flash.c. Phase 2c will fold this into
// a single Secure-side storage module once the keystore moves over.
#define HWM_SECTOR_SIZE        4096u
#define HWM_TOTAL_SLOTS_LOCAL  16u
#define HWM_SECTORS_PER_SLOT   (HWM_FLASH_SIZE / HWM_SECTOR_SIZE / HWM_TOTAL_SLOTS_LOCAL)
#define HWM_BYTES_PER_SLOT     (HWM_SECTORS_PER_SLOT * HWM_SECTOR_SIZE)

// --- Phase 2a smoke-test veneer -------------------------------------------
//
// Round-trips a value with a known bit-flip so NS can verify the SG path
// works end-to-end before any real veneers go in. Remove once Phase 2b
// (chains/HWM) is shipping.
__attribute__((cmse_nonsecure_entry))
uint32_t s_phase2_test(uint32_t x) {
    return x ^ 0xA5A5A5A5u;
}

// --- Phase 2b: flash veneers --------------------------------------------
//
// Each function below is a Secure Gateway entry into Secure flash code.
// The pointer-bearing veneers MUST validate the buffer is in NS memory
// before reading. cmse_check_pointed_object() returns NULL if the buffer
// straddles Secure memory or is not NS-readable, in which case the
// veneer refuses with NEG_PTR. This is the M9 boundary's primary
// argument-validation primitive.
#define M9_NEG_PTR    (-101)
#define M9_NEG_RANGE  (-102)

__attribute__((cmse_nonsecure_entry))
int s_flash_write_chains_page(const void *page, size_t len) {
    if (len != CHAINS_FLASH_SIZE) return M9_NEG_RANGE;
    const void *checked = cmse_check_address_range(
        (void *)page, len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!checked) return M9_NEG_PTR;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(CHAINS_FLASH_OFFSET, CHAINS_FLASH_SIZE);
    flash_range_program(CHAINS_FLASH_OFFSET, (const uint8_t *)checked, len);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_slot(uint8_t slot_idx) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    uint32_t off = HWM_FLASH_OFFSET + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(off, HWM_BYTES_PER_SLOT);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_sector(uint8_t slot_idx, uint8_t sector_in_slot) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    if (sector_in_slot >= HWM_SECTORS_PER_SLOT) return M9_NEG_RANGE;
    uint32_t off = HWM_FLASH_OFFSET
                 + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT
                 + (uint32_t)sector_in_slot * HWM_SECTOR_SIZE;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(off, HWM_SECTOR_SIZE);
    restore_interrupts(ints);
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_flash_erase_hwm_all(void) {
    uint32_t ints = save_and_disable_interrupts();
    flash_range_erase(HWM_FLASH_OFFSET, HWM_FLASH_SIZE);
    restore_interrupts(ints);
    return 0;
}

// --- Phase 2c: keystore-backed signing veneers -------------------------
//
// Walks an NS-supplied SLIP-10 path string through the Secure-side seed
// (TEST_SEED, replaced by encrypted+PIN-unlocked seed in M9.5) and
// returns the public key (s_get_pubkey) or a 32-byte SC-challenge
// signature (s_sign_sc_challenge). Privval canonical sign-bytes routes
// through the larger HWM-fused veneer (Phase 2c3).
//
// The path string is treated as length-bounded by KEYSTORE_MAX_PATH_LEN
// scanning during cmse_check_address_range; we pass a generous upper
// bound and the keystore's own parser bails on anything malformed.
#define M9_KEYSTORE_MAX_PATH_LEN  128u

// --- Phase 2e: TRNG access ---------------------------------------------
//
// The RP2350 TRNG sits at 0x400F0000. ACCESSCTRL_TRNG is opened to NS in
// Phase 1 (closed back to Secure-only in Phase 4), but we route random
// reads through this veneer anyway so the entropy path stays anchored
// in Secure once Phase 4 lands. The hardware emits 192 bits per cycle
// across EHR_DATA0..5; we cache the unused words between calls.
#define TRNG_BASE_S            0x400F0000u
#define TRNG_RND_SOURCE_ENABLE (*(volatile uint32_t *)(TRNG_BASE_S + 0x12Cu))
#define TRNG_TRNG_VALID        (*(volatile uint32_t *)(TRNG_BASE_S + 0x110u))
#define TRNG_RNG_ICR           (*(volatile uint32_t *)(TRNG_BASE_S + 0x108u))
#define TRNG_EHR_DATA0_ADDR    ((volatile uint32_t *)(TRNG_BASE_S + 0x114u))

static uint32_t s_trng_buf[6];
static uint32_t s_trng_pos = 6;
static bool     s_trng_enabled = false;

static uint32_t m9_trng_word(void) {
    if (!s_trng_enabled) {
        TRNG_RND_SOURCE_ENABLE = 1u;
        s_trng_enabled = true;
    }
    if (s_trng_pos >= 6u) {
        while (!(TRNG_TRNG_VALID & 1u)) { /* spin until 192 bits ready */ }
        for (int i = 0; i < 6; i++) s_trng_buf[i] = TRNG_EHR_DATA0_ADDR[i];
        // Writing 1 to RNG_ICR's interrupt bits clears VALID so the next
        // batch starts collecting. The 0x3F mask covers all six EHR_*
        // valid-ready bits the bootrom uses; harmless to write spares.
        TRNG_RNG_ICR = 0x3Fu;
        s_trng_pos = 0;
    }
    return s_trng_buf[s_trng_pos++];
}

// --- Phase 2d: trusted input -------------------------------------------
//
// Read button state via Secure-side GPIO. Buttons are GPIO 16 (LEFT) and
// 17 (RIGHT), wired with internal pull-ups -- active-low. The SIO
// GPIO_IN register at 0xD0000004 reflects the pad regardless of who
// configured the pin function, so this veneer works even after Phase 4
// clears GPIO_NSMASK bits 16/17 to take the pad config away from NS.
//
// Returns true if the button is currently held.
__attribute__((cmse_nonsecure_entry))
bool s_input_pressed(uint8_t btn) {
    uint32_t pin;
    if (btn == 0u) pin = 16u;       // INPUT_BTN_LEFT
    else if (btn == 1u) pin = 17u;  // INPUT_BTN_RIGHT
    else return false;
    uint32_t in = *(volatile uint32_t *)0xD0000004u;  // SIO_GPIO_IN
    return (in & (1u << pin)) == 0u;
}

__attribute__((cmse_nonsecure_entry))
int s_random(uint8_t *out, size_t n) {
    if (!out || n == 0) return M9_NEG_PTR;
    if (n > 4096u) return M9_NEG_RANGE;
    const void *out_chk = cmse_check_address_range(
        out, n, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!out_chk) return M9_NEG_PTR;
    uint8_t *p = (uint8_t *)out_chk;
    size_t i = 0;
    while (i + 4u <= n) {
        uint32_t w = m9_trng_word();
        p[i + 0] = (uint8_t)(w);
        p[i + 1] = (uint8_t)(w >> 8);
        p[i + 2] = (uint8_t)(w >> 16);
        p[i + 3] = (uint8_t)(w >> 24);
        i += 4;
    }
    if (i < n) {
        uint32_t w = m9_trng_word();
        for (size_t j = 0; j < n - i; j++) p[i + j] = (uint8_t)(w >> (8 * j));
    }
    return 0;
}

__attribute__((cmse_nonsecure_entry))
int s_get_pubkey(uint8_t curve, const char *path, uint8_t out_pubkey[32]) {
    if (!path || !out_pubkey) return M9_NEG_PTR;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *out_chk = cmse_check_address_range(
        out_pubkey, 32, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!out_chk) return M9_NEG_PTR;
    size_t out_len = 0;
    return os_crypto_get_pubkey((os_curve_t)curve, path, out_pubkey, 32, &out_len);
}

// Phase 2c3: fused HWM-check + sign. Secure looks up the slot's chain_id
// from the Secure-side chain config cache so NS can't lie about which
// chain it's signing for. If HWM strict-advance succeeds the new record
// is persisted before the signature is generated; if it fails the
// signature is never computed.
//
// Return codes: 0 success; -1 HWM rejected; -2 slot not configured;
// other negative codes from os_crypto_sign / pointer validation.
__attribute__((cmse_nonsecure_entry))
int s_sign_and_advance(const s_sign_and_advance_args_t *args) {
    if (!args) return M9_NEG_PTR;
    const s_sign_and_advance_args_t *a = cmse_check_address_range(
        (void *)args, sizeof(*args), CMSE_NONSECURE | CMSE_MPU_READ);
    if (!a) return M9_NEG_PTR;
    // Copy out so we touch each field exactly once (NS could TOCTOU on
    // a shared struct).
    s_sign_and_advance_args_t v = *a;
    if (!v.path || !v.data || !v.out_sig) return M9_NEG_PTR;
    if (v.data_len == 0 || v.data_len > 4096u) return M9_NEG_RANGE;
    if (v.hwm_slot_idx >= HWM_TOTAL_SLOTS) return M9_NEG_RANGE;
    if (!cmse_check_address_range((void *)v.path, 1,
                                  CMSE_NONSECURE | CMSE_MPU_READ)) return M9_NEG_PTR;
    if (!cmse_check_address_range((void *)v.data, v.data_len,
                                  CMSE_NONSECURE | CMSE_MPU_READ)) return M9_NEG_PTR;
    if (!cmse_check_address_range(v.out_sig, 64,
                                  CMSE_NONSECURE | CMSE_MPU_READWRITE)) return M9_NEG_PTR;

    // Look up the chain config slot for this HWM index. The mapping is
    // cosmos[0..7] -> hwm 0..7, gno[0..7] -> hwm 8..15.
    chains_family_t fam   = (v.hwm_slot_idx < 8u) ? CHAINS_FAMILY_COSMOS : CHAINS_FAMILY_GNO;
    size_t          slot  = (v.hwm_slot_idx < 8u) ? v.hwm_slot_idx
                                                  : (size_t)(v.hwm_slot_idx - 8u);
    const chain_slot_t *cs = chains_get(fam, slot);
    if (!cs || !cs->in_use) return -2;

    // HWM strict-advance using the slot's chain_id (Secure's truth).
    // chain_id strlen is bounded by CHAINS_CHAIN_ID_MAX, set at config-add.
    size_t cid_len = 0;
    while (cid_len < CHAINS_CHAIN_ID_MAX && cs->chain_id[cid_len] != '\0') cid_len++;
    if (!hwm_advance(v.hwm_slot_idx, cs->chain_id, cid_len,
                     v.type, v.height, v.round)) {
        return -1;
    }

    // HWM accepted -- now sign. Per the M9.2 design these must be
    // atomic from NS's perspective: if either step fails we still
    // honor the HWM advance (the height is "used"), so a sign failure
    // wedges this height for the slot but doesn't let NS retry-double-
    // sign at the same height.
    return os_crypto_sign((os_curve_t)v.curve, v.path,
                          v.data, v.data_len, v.out_sig);
}

__attribute__((cmse_nonsecure_entry))
int s_sign_privval(const char *path, const uint8_t *data, size_t data_len,
                   uint8_t out_sig[64]) {
    if (!path || !data || !out_sig) return M9_NEG_PTR;
    if (data_len == 0 || data_len > 4096u) return M9_NEG_RANGE;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *data_chk = cmse_check_address_range(
        (void *)data, data_len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!data_chk) return M9_NEG_PTR;
    const void *sig_chk = cmse_check_address_range(
        out_sig, 64, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!sig_chk) return M9_NEG_PTR;
    // Curve is fixed to Ed25519 here; the privval protocol on both
    // Cosmos and Gno chains uses Ed25519 only. cmse_nonsecure_entry's
    // 4-register limit forced dropping the curve arg.
    return os_crypto_sign(OS_CURVE_ED25519, path, data, data_len, out_sig);
}

__attribute__((cmse_nonsecure_entry))
int s_sign_sc_challenge(uint8_t curve, const char *path,
                        const uint8_t challenge[32], uint8_t out_sig[64]) {
    if (!path || !challenge || !out_sig) return M9_NEG_PTR;
    const void *path_chk = cmse_check_address_range(
        (void *)path, 1, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!path_chk) return M9_NEG_PTR;
    const void *chal_chk = cmse_check_address_range(
        (void *)challenge, 32, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!chal_chk) return M9_NEG_PTR;
    const void *sig_chk = cmse_check_address_range(
        out_sig, 64, CMSE_NONSECURE | CMSE_MPU_READWRITE);
    if (!sig_chk) return M9_NEG_PTR;
    // Length-locked to 32 bytes here: this veneer cannot be turned into
    // a general-purpose signing oracle. Privval canonical sign-bytes
    // (variable length) route through Phase 2c3's s_sign_and_advance.
    return os_crypto_sign((os_curve_t)curve, path, challenge, 32, out_sig);
}

// --- Phase 2d: display + UI veneers ------------------------------------
//
// SPI1 + the e-paper panel + framebuffer + Pico_ePaper_Code library +
// the UI layout code (splash, console, mode_select, confirm) all live
// in the Secure image. NS holds no paint API and no framebuffer
// pointer; it can only push text or request canned screens.
//
// Each veneer below either: forwards directly to a Secure-side
// implementation (display_init, console_render, etc., compiled into
// picowallet_secure with PICOWALLET_SECURE_BUILD=1), or validates an NS
// pointer/length first.
//
// console_log is the only one with a variable-length NS input. We bound
// it at S_CONSOLE_LOG_MAX so cmse_check_address_range has a definite
// range; the underlying push_one truncates further to MAX_LINE_LEN.
#define S_CONSOLE_LOG_MAX  256u

__attribute__((cmse_nonsecure_entry))
void s_display_init(void) {
    display_init();
}

__attribute__((cmse_nonsecure_entry))
void s_splash_render(void) {
    splash_render();
}

__attribute__((cmse_nonsecure_entry))
void s_console_init(void) {
    console_init();
}

__attribute__((cmse_nonsecure_entry))
void s_console_clear_history(void) {
    console_clear_history();
}

__attribute__((cmse_nonsecure_entry))
void s_console_log(const char *line, size_t len) {
    if (!line || len == 0) return;
    if (len > S_CONSOLE_LOG_MAX) len = S_CONSOLE_LOG_MAX;
    const void *chk = cmse_check_address_range(
        (void *)line, len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!chk) return;
    // Copy locally + ensure NUL-terminated before handing to the
    // Secure-side console which expects a C string. The NS-supplied
    // string may not include a NUL within `len` (caller may pass
    // strlen instead of strlen+1); we force one.
    char local[S_CONSOLE_LOG_MAX];
    memcpy(local, chk, len);
    local[len < S_CONSOLE_LOG_MAX ? len : S_CONSOLE_LOG_MAX - 1] = '\0';
    local[S_CONSOLE_LOG_MAX - 1] = '\0';
    console_log(local);
}

__attribute__((cmse_nonsecure_entry))
bool s_console_is_dirty(void) {
    return console_is_dirty();
}

__attribute__((cmse_nonsecure_entry))
void s_console_render(void) {
    console_render();
}

__attribute__((cmse_nonsecure_entry))
void s_console_render_clean(void) {
    console_render_clean();
}

__attribute__((cmse_nonsecure_entry))
uint8_t s_mode_select_prompt(void) {
    return (uint8_t)mode_select_prompt();
}

__attribute__((cmse_nonsecure_entry))
bool s_factory_reset_with_consent(void) {
    return factory_reset_confirm();
}

__attribute__((cmse_nonsecure_entry))
int s_flash_write_hwm_page(uint8_t slot_idx, uint16_t page_in_slot,
                           const void *page, size_t len) {
    if (slot_idx >= HWM_TOTAL_SLOTS_LOCAL) return M9_NEG_RANGE;
    if (len != 256u) return M9_NEG_RANGE;        // pico-sdk FLASH_PAGE_SIZE
    uint32_t slot_pages = HWM_BYTES_PER_SLOT / 256u;
    if (page_in_slot >= slot_pages) return M9_NEG_RANGE;
    const void *checked = cmse_check_address_range(
        (void *)page, len, CMSE_NONSECURE | CMSE_MPU_READ);
    if (!checked) return M9_NEG_PTR;
    uint32_t off = HWM_FLASH_OFFSET
                 + (uint32_t)slot_idx * HWM_BYTES_PER_SLOT
                 + (uint32_t)page_in_slot * 256u;
    uint32_t ints = save_and_disable_interrupts();
    flash_range_program(off, (const uint8_t *)checked, len);
    restore_interrupts(ints);
    return 0;
}
