#!/usr/bin/env python3
"""Convert a PNG into a 1-bit packed C header for the PicoWallet splash.

Output format:
    static const uint8_t SPLASH_IMG[N] = { ... };
    #define SPLASH_IMG_WIDTH  W
    #define SPLASH_IMG_HEIGHT H

Pixels are packed row-major, MSB-first, with a 1 bit meaning BLACK.

Usage:
    python3 tools/png_to_header.py <input.png> <output.h> [--width W] [--height H]

If the input doesn't match the target dimensions, it is scaled (preserving
aspect ratio) into a white canvas of the target size and centered.
"""

import argparse
import sys

from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--width",  type=int, default=480)
    ap.add_argument("--height", type=int, default=None,
                    help="target height; if omitted, uses input height (no rescale unless --width set)")
    ap.add_argument("--threshold", type=int, default=128,
                    help="luma threshold for black/white (0-255). Default 128.")
    ap.add_argument("--name", default="SPLASH_IMG",
                    help="C identifier prefix (default SPLASH_IMG)")
    args = ap.parse_args()

    img = Image.open(args.input).convert("L")  # grayscale
    src_w, src_h = img.size

    tgt_w = args.width
    tgt_h = args.height if args.height is not None else src_h

    if (src_w, src_h) != (tgt_w, tgt_h):
        # Fit-to-target, centered, white background.
        canvas = Image.new("L", (tgt_w, tgt_h), 255)
        ratio = min(tgt_w / src_w, tgt_h / src_h)
        new_w = max(1, int(round(src_w * ratio)))
        new_h = max(1, int(round(src_h * ratio)))
        scaled = img.resize((new_w, new_h), Image.LANCZOS)
        canvas.paste(scaled, ((tgt_w - new_w) // 2, (tgt_h - new_h) // 2))
        img = canvas

    # Threshold to 1-bit: black = pixel < threshold
    pixels = img.load()
    bytes_per_row = (tgt_w + 7) // 8
    out = bytearray(bytes_per_row * tgt_h)
    for y in range(tgt_h):
        for byte_x in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < tgt_w and pixels[x, y] < args.threshold:
                    b |= 1 << (7 - bit)
            out[y * bytes_per_row + byte_x] = b

    name = args.name
    with open(args.output, "w") as f:
        f.write("// AUTO-GENERATED by tools/png_to_header.py - DO NOT EDIT BY HAND.\n")
        f.write(f"// Source: {args.input}\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {name}_WIDTH  {tgt_w}\n")
        f.write(f"#define {name}_HEIGHT {tgt_h}\n\n")
        f.write(f"static const uint8_t {name}[{len(out)}] = {{\n")
        for i in range(0, len(out), 16):
            row = ", ".join(f"0x{b:02x}" for b in out[i:i+16])
            f.write(f"    {row},\n")
        f.write("};\n")

    print(f"wrote {args.output}: {tgt_w}x{tgt_h}, {len(out)} bytes",
          file=sys.stderr)


if __name__ == "__main__":
    main()
